# Base image: really weightless
image: python:latest

stages:
  - develop
  - production

develop:
  stage: develop
  script: python setup.py bdist_wheel
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
  only:
    - develop

master:
  stage: production
  script:
    - pip install twine
    - python setup.py sdist bdist_wheel
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --verbose --repository-url https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  only:
    - master
    - /^(v)[0-9]*.[0-9]*.[0-9]*$/